### ISSUE TITLE
question for self.codebooks_used[min_indices] += 1

### ISSUE THREAD

**Issue by rickwang101** [MHVali/Noise-Substitution-in-Vector-Quantization#2]
Hi MHVali,

Thanks so much for the amazing paper and code!

I have a question for line 85 of NSVQ.py: 
```
self.codebooks_used[min_indices] += 1". 
```
This will increase the counter by one even for repeating indices. Is this the intended method or do you want to count all occurrences of repeating indices by using a for loop?
```
    for index in min_indices:
        self.codebooks_used[index] += 1
```
Thanks,
Wei

**Comment by MHVali** [comment]
Hi @rickwang101,
Yes! The main intention is that to add one to the indices (even repeated) which are used for VQ in that training batch. So, for example after 100 training batches, we would have the number of times each codebook element is used for VQ process (the repetition is not important) for 100 tries. After having the usage value in "self.codebooks_used" variable, we can discard the ones which are used less than a threshold (discarding_threshold) in "codebook_replacement" function.

**Comment by rickwang101** [comment]
Got it. Thanks!
