### ISSUE TITLE
Paranthesis error in NSVQ

### ISSUE THREAD

**Issue by jacobgorm** [MHVali/Noise-Substitution-in-Vector-Quantization#3]
hi, there seems to be a small issue with this code:

     # defining vector quantization error
        vq_error = (norm_quantization_residual / norm_random_vector + self.eps) * random_vector

I suppose self.eps is used to avoid division by zero, but in that case the parentheses appear to be placed wrong.

**Comment by MHVali** [comment]
Hi,

Thanks for your comment! I corrected it.
